# -*- coding: utf-8 -*-
"""Train_nn_inner_outer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189KvI2DvkZYgFKVA4nLTbTwCniGO4UZB
"""

# Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive', force_remount = True)

# Import packages
import cv2
import os, gc, sys, glob
import pandas as pd
import numpy as np
from tqdm import tqdm
from pathlib import Path
import matplotlib.pyplot as plt
import itertools
import random
import datetime
import time
import tempfile
from subprocess import check_output

import imblearn
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler

from sklearn import model_selection
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, GroupShuffleSplit, StratifiedKFold
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import auc, roc_curve
from sklearn.utils import shuffle
from skimage.transform import rotate

import keras
from keras import optimizers, applications
from keras.models import Sequential, Model, load_model
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from keras.callbacks import ReduceLROnPlateau, TensorBoard, ModelCheckpoint, CSVLogger
from keras.optimizers import Adam
from keras.layers.normalization import BatchNormalization
from keras.metrics import categorical_accuracy
from keras.preprocessing.image import ImageDataGenerator
import keras.backend as K

import tensorflow as tf

print(tf.__version__)

# Initialize TPU
try:
  tpu = tf.distribute.cluster_resolver.TPUClusterResolver()  # TPU detection
  print('Running on TPU ', tpu.cluster_spec().as_dict()['worker'])
except ValueError:
  raise BaseException('ERROR: Not connected to a TPU runtime; please see the previous cell in this notebook for instructions!')

tf.config.experimental_connect_to_cluster(tpu)
tf.tpu.experimental.initialize_tpu_system(tpu)
tpu_strategy = tf.distribute.TPUStrategy(tpu)

from google.colab import auth
auth.authenticate_user()

"""#1. Functions to extract, split and balance dataset"""

def split_data(file_names):

    indices = np.arange(len(file_names))
    labels = [f.split('/')[-2] for f in file_names]

    # Split train - test
    ind_train, ind_test = train_test_split(indices,
                                            test_size=0.10,
                                            random_state=42,
                                            stratify=labels,
                                            shuffle=True)
    # Split train - validation
    ind_train, ind_val = train_test_split(ind_train,
                                            test_size=0.15/0.9,
                                            random_state=42,
                                            stratify=[labels[i] for i in ind_train])

    return ind_train, ind_val, ind_test

# Tackle class imbalanceness: Choose under- or oversampling
def balance_dataset(file_names, ind, strategy):
      labels = [file_names[i].split('/')[-2] for i in ind]

      # Define strategy
      if strategy == 'Oversample':
        sample_strat = RandomOverSampler(sampling_strategy='minority')
      if strategy == 'Undersample':
        sample_strat = RandomUnderSampler(sampling_strategy='majority')

      # Fit and apply the transform
      ind_new, labels_balanced = sample_strat.fit_resample(np.arange(len(labels)).reshape(-1, 1), labels)
      ind_new = ind[ind_new].squeeze()

      return ind_new

"""# 2. Functions to convert set of PNG files to TFRecord Dataset - required for TPU"""

# Read image and label
def decode_png_and_label(file_name):
  bits = tf.io.read_file(file_name)
  image = tf.io.decode_png(bits)

  # parse flower name from containing directory
  label = tf.strings.split(tf.expand_dims(file_name, axis=-1), sep='/')
  label = label.values[-2]
  return image, label

# Encode image to bytestring to convert to TFrecord
def recompress_image(image, label):
  image = tf.cast(image, tf.uint8)
  image = tf.image.encode_png(image)
  return image, label

# function to display 9 images from TF dataset
def display_9_images_from_dataset(dataset):
    plt.figure(figsize=(13,13))
    subplot=331
    for i, (image, label) in enumerate(dataset):
        plt.subplot(subplot)
        plt.axis('off')
        plt.imshow(image.numpy().astype(np.uint8))
        plt.title(label.numpy().decode("utf-8"), fontsize=16)
        subplot += 1
        if i==8:
            break
    plt.tight_layout()
    plt.subplots_adjust(wspace=0.1, hspace=0.1)
    plt.show()

# Define different feature types
def _bytestring_feature(list_of_bytestrings):
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=list_of_bytestrings))

def _int_feature(list_of_ints): # int64
  return tf.train.Feature(int64_list=tf.train.Int64List(value=list_of_ints))

def _float_feature(list_of_floats): # float32
  return tf.train.Feature(float_list=tf.train.FloatList(value=list_of_floats))

# Convert files to TFRecord
def to_tfrecord(tfrec_filewriter, img_bytes, label):
  class_num = np.argmax(np.array(class_names)==label.decode('utf8')) # 'roses' => 2 (order defined in CLASSES)
  one_hot_class = np.eye(len(class_names))[class_num]     # [0, 0, 1, 0, 0] for class #2, roses

  feature = {
      "image": _bytestring_feature([img_bytes]), # one image in the list
      "label": _bytestring_feature([label]),     # one label in the list
      "class_num": _int_feature([class_num]), # label converted to int
  }
  return tf.train.Example(features=tf.train.Features(feature=feature))

# Save images to .TFREC file - each file containing shard_size images
def create_tf_dataset(dataset, shard_size, data_path, set_type):
  dataset = dataset.batch(shard_size)
  for shard, (image, label) in enumerate(dataset):
    shard_size = image.numpy().shape[0]
    print(shard_size)
    # good practice to have the number of records in the filename
    filename = data_path + 'trainset.tfrec'

    with tf.io.TFRecordWriter(filename) as out_file:
      for i in range(shard_size):
        if i % 500 == 0:
          print(i)
        example = to_tfrecord(out_file,
                              image.numpy()[i], # re-compressed image: already a byte string
                              label.numpy()[i])
        out_file.write(example.SerializeToString())
      print("Wrote file {} containing records".format(filename))

"""# Test first part of pipeline

"""

AUTO = tf.data.experimental.AUTOTUNE

# Main directory containing subdirectory per path - in Google Cloud Storage
data_path = 'gs://tpu_umcg/data/'

# Extracting filenames and classnames
file_names = tf.io.gfile.glob(data_path + '*/*.png')
class_names = np.unique([f.split('/')[-2] for f in file_names])

# Split data into train, test, validation
# Balance train set
ind_train, ind_val, ind_test = split_data(file_names)
ind_train = balance_dataset(file_names, ind_train, 'Oversample')

fn_train = [file_names[i] for i in ind_train]
fn_train = random.sample(fn_train, 1500)
fn_val = [file_names[i] for i in ind_val]
fn_test = [file_names[i] for i in ind_test]

# Convert filename sets to tensors
fn_train_tf = tf.data.Dataset.from_tensor_slices(fn_train)
fn_val_tf = tf.data.Dataset.from_tensor_slices(fn_val)

# Perform steps to save file as TFRecord
train_set_dec = fn_train_tf.map(decode_png_and_label, num_parallel_calls=AUTO)
train_set_enc = train_set_dec.map(recompress_image, num_parallel_calls=AUTO)

#val_set_dec = fn_val_tf.map(decode_png_and_label, num_parallel_calls=AUTO)
#val_set_enc = val_set_dec.map(recompress_image, num_parallel_calls=AUTO)

# Display images and labels
# Print imageshapes and labels (per batch of 9 images)
display_9_images_from_dataset(train_set_dec)
display_dataset = train_set_dec.batch(9)
for image, label in display_dataset.take(30):
  print("Image batch shape {}, {})".format(image.numpy().shape, [lbl.decode('utf8') for lbl in label.numpy()]))

# Save train and validation set as TFRecord
#create_tf_dataset(train_set_enc, len(fn_train), data_path, 'train_data')
#create_tf_dataset(val_set_enc, len(fn_train), data_path, 'validation_data')

"""# VANAF HIER: INLEZEN TFRECORDDATA + MODEL DRAAIEN
Useful links:
- https://keras.io/examples/vision/xray_classification_with_tpus/
- https://colab.research.google.com/github/GoogleCloudPlatform/training-data-analyst/blob/master/courses/fast-and-lean-data-science/03_Flower_pictures_to_TFRecords.ipynb#scrollTo=oYzgji7agVg4
- https://colab.research.google.com/notebooks/tpu.ipynb#scrollTo=LtAVr-4CP1rp
"""

def fit_model(model, batch_size, epochs, output_path,
              train_data):

    reduce_lr = ReduceLROnPlateau(monitor='val_loss',
                              patience=30,
                              verbose=1,
                              factor=0.5,
                              cooldown=0,
                              min_delta=0.0001,
                              min_lr=0.00001)

    # cp_weights_auc = ModelCheckpoint(output_path + "/weights.hdf5", monitor='val_auc', verbose=1,
    #                                 save_best_only=True, mode='max', period=1)
    # cp_weights_loss = ModelCheckpoint(output_path + "/weights_loss.hdf5", monitor='val_loss', verbose=1,
    #                                 save_best_only=True, mode='min', period=1)

    # filepath="weights-improvement-{epoch:02d}-{val_auc:.2f}.hdf5"
    # cp_weights_2 = ModelCheckpoint(output_path + '/' + filepath, monitor='val_auc', verbose=1, save_best_only=False, mode='max', period=50)

    # Fit model
    # history = model.fit(datagen.flow(X_train, y_train, batch_size=batch_size),
    #                 steps_per_epoch = len(X_train) / batch_size,
    #                 epochs = epochs,
    #                 verbose = 1,
    #                 validation_data=(X_val, y_val),
    #                 callbacks=[reduce_lr, cp_weights_auc, cp_weights_loss, cp_weights_2])

    history = model.fit(train_data,
                    steps_per_epoch = len(fn_train) / batch_size,
                    epochs = epochs,
                    verbose = 1)


    history_df = pd.DataFrame(history.history) #.to_csv(output_path + "/history.csv")

    return model, history

def parse_tfrecord(example, img_size=(224, 224)):
  features = {
    "image": tf.io.FixedLenFeature([], tf.string), # tf.string means bytestring
    "label": tf.io.FixedLenFeature([], tf.string),  # shape [] means scalar
    "class_num": tf.io.FixedLenFeature([], tf.int64),
  }
  example = tf.io.parse_single_example(example, features)
  decoded = tf.image.decode_png(example['image'], channels=3)
  normalized = tf.cast(decoded, tf.float32) / 255.0 # convert each 0-255 value to floats in [0, 1] range
  image_tensor = tf.image.resize(normalized, img_size)
  label = example['label']
  class_num = example['class_num']
  return image_tensor, class_num

def load_dataset(file_names):
  # Read from TFRecords. For optimal performance, we interleave reads from multiple files.
  records = tf.data.TFRecordDataset(file_names, num_parallel_reads=AUTO)
  return records.map(parse_tfrecord, num_parallel_calls=AUTO)

def get_training_dataset(file_names):
  dataset = load_dataset(file_names)

  # Create some additional training images by randomly flipping and
  # increasing/decreasing the saturation of images in the training set.
  def data_augment(image, one_hot_class):
    modified = tf.image.random_flip_left_right(image)
    modified = tf.image.random_saturation(modified, 0, 2)
    return modified, one_hot_class
  augmented = dataset.map(data_augment, num_parallel_calls=AUTO)

  # Prefetch the next batch while training (autotune prefetch buffer size).
  return augmented.repeat().shuffle(2048).batch(batch_size).prefetch(AUTO)

AUTO = tf.data.experimental.AUTOTUNE

# Main directory containing subdirectory per path - in Google Cloud Storage
data_path = 'gs://tpu_umcg/data/'

batch_size = 32 * tpu_strategy.num_replicas_in_sync
class_imb_type = 'Oversample'
tf_model = 'ResNet'
full_retrain = False
freeze_till_block = 0
lr = 0.001
decay = 0
dr = 0.4
loss_func = 'binary_crossentropy'
epochs = 20

folder_name = tf_model + '_class_imb_type_' + class_imb_type + '_' + 'retrain_' + str(full_retrain) + '_' + str(freeze_till_block) + '_'+ str(lr).replace('.','') + '_'+ str(decay) + '_' + str(dr).replace('.','') + '_' + str(epochs)
output_path = data_path + folder_name

gcs_pattern = 'gs://tpu_umcg/data/*.tfrec'
file_names = tf.io.gfile.glob(gcs_pattern)
training_data = get_training_dataset(file_names)

for image, class_num in training_data.take(20):
  print("Image batch shape {}, {})".format(image.numpy().shape, class_num)) #label.numpy()[0].decode('utf8')

# Creating the model in the TPUStrategy scope means we will train the model on the TPU
print('Building and fitting model ' + tf_model
      + ' model with parameters: train base = ' + str(full_retrain)
      + ', freeze till block = ' + str(freeze_till_block)
      + ', learning rate = ' + str(lr)
      + ', decay rate = ' + str(decay)
      + ', dropout rate = ' + str(dr))

with tpu_strategy.scope():
  model = build_model(tf_model, full_retrain, freeze_till_block, loss_func, lr, decay, dr)

history = model.fit(training_data,
          steps_per_epoch = len(fn_train) / batch_size,
          epochs = epochs,
          verbose = 1)

#fit_model(model, batch_size, epochs, output_path, training_data)
# for writing files to GCS: https://colab.research.google.com/notebooks/io.ipynb#scrollTo=S7c8WYyQdh5i

history_df = pd.DataFrame(history.history)

!gcloud config set project 'powerful-unison-271911'

history_df.to_csv("/tmp/history.csv")

bucket_name = folder_name.lower()

!gsutil mb gs://{bucket_name}

!gsutil cp /tmp/history.csv gs://{bucket_name}

# Read single image
def read_img(img_path, size):
    img = cv2.imread(str(img_path))
    img = cv2.resize(img, (size[0], size[1]))
    return img

# Loading data and labels
def read_data(main_path, size):
    folders = os.listdir(main_path)
    dirs = [main_path + '/' + f for f in folders]

    data = []
    labels = []

    for img_path in Path(dirs[0]).glob('**/*.png'):
        data.append(read_img(img_path, size))
        labels.append([os.path.basename(img_path), folders[0]])

    for img_path in Path(dirs[1]).glob('**/*.png'):
        data.append(read_img(img_path, size))
        labels.append([os.path.basename(img_path), folders[1]])

    data = np.array(data, np.float32) / 255

    label_encoder = LabelEncoder()
    labels = pd.DataFrame(labels, columns = ['Image','Label'])
    labels['Tiff'] = [name[:name.find('_')] for name in labels['Image']]
    enc_labels = label_encoder.fit_transform(np.array(labels.iloc[:,1]))

    return data, labels, enc_labels

# Split train, validation and test set
# param independent determines if test data is independent or not
# (random or specific WSIs excluded from training)
def split_data(data, enc_labels, labels, independent):

    indices = np.arange(len(labels))

    if not independent:
        # Split train - test
        ind_train, ind_test = train_test_split(indices,
                                                test_size=0.10,
                                                random_state=42,
                                                stratify=labels['Tiff'],
                                                shuffle=True)
        # Split train - validation
        ind_train, ind_val = train_test_split(ind_train,
                                                test_size=0.15/0.9,
                                                random_state=42,
                                                stratify=labels.iloc[ind_train,-1])

    else:
        # Initialize group splitter, based on Tiff key
        split_tr_te = GroupShuffleSplit(n_splits=2, train_size=.9, random_state=42)
        split_tr_val = GroupShuffleSplit(n_splits=2, train_size=.75, random_state=42)

        # Split train - test and train - validation
        ind_train, ind_test = next(split_tr_te.split(data, groups=labels['Tiff']))
        ind_train, ind_val = next(split_tr_val.split(data[ind_train], groups=labels.iloc[ind_train,-1]))

        X_train = data[ind_train]
        y_train = enc_labels[ind_train]
        X_test = data[ind_test]
        y_test = enc_labels[ind_test]
        X_val = data[ind_val]
        y_val = enc_labels[ind_val]

    return ind_train, ind_val, ind_test

# Tackle class imbalanceness: Choose under- or oversampling
def balance_dataset(y, ind, strategy, type):
      y_train = y[ind_train]

      # Define strategy
      if strategy == 'Oversample':
        sample_strat = RandomOverSampler(sampling_strategy='minority')
      if strategy == 'Undersample':
        sample_strat = RandomUnderSampler(sampling_strategy='majority')

      # Fit and apply the transform
      if type == 'class':
        ind_new, y_train_new = sample_strat.fit_resample(np.arange(len(y_train)).reshape(-1, 1), y_train)
      if type == 'tiff':
        comb_class_tiff = y_train.astype(str) + labels['Tiff'][ind_train]
        ind_new, comb_class_tiff_new = sample_strat.fit_resample(np.arange(len(comb_class_tiff)).reshape(-1, 1), comb_class_tiff)
        y_train_new = y[ind_new]

      ind_train_new = ind_train[ind_new].squeeze()

      return ind_train_new

def get_data_sets(X, y, ind_train, ind_val, ind_test):

    X_train = X[ind_train].squeeze()
    y_train = y[ind_train].squeeze()
    X_test = X[ind_test]
    y_test = y[ind_test]
    X_val = X[ind_val]
    y_val = y[ind_val]

    perc_out_train = sum(y_train)/len(y_train)*100
    perc_out_val = sum(y_val)/len(y_val)*100
    perc_out_test = sum(y_test)/len(y_test)*100

    print('Percentage of class outside in train set ' + str(perc_out_train))
    print('Percentage of class outside in validation set ' + str(perc_out_val))
    print('Percentage of class outside in test set ' + str(perc_out_test))

    return X_train, y_train, X_val, y_val, X_test, y_test


def convert_to_tf_prefetchdataset(X, y, batch_size):
    image_data = tf.data.Dataset.from_tensor_slices(X)
    labels_data = tf.data.Dataset.from_tensor_slices(y)
    dataset = tf.data.Dataset.zip((image_data, labels_data))
    dataset = dataset.cache()  # this small dataset can be entirely cached in RAM
    dataset = dataset.shuffle(5000, reshuffle_each_iteration=True)
    dataset = dataset.repeat() # Mandatory for Keras for now
    dataset = dataset.batch(batch_size, drop_remainder=True) # drop_remainder is important on TPU, batch size must be fixed
    dataset = dataset.prefetch(-1)
    return dataset

# Build model
# Another option: Add differential learning
    # https://github.com/gunchagarg/differential-learning-rate-keras
def build_model(tf_model, full_retrain, freeze_till_block, loss_func, lr, decay, dr):

    # Select base model
    img_rows, img_cols, img_channel = 224, 224, 3
    if tf_model == 'InceptionV3':
        base_model = applications.inception_v3.InceptionV3(include_top=False,
                                                   weights='imagenet',
                                                   pooling='avg',
                                                   input_shape=(img_rows, img_cols, img_channel))

        lay_num_freeze = int(inceptionV3_blocks[freeze_till_block,2])

    if tf_model == 'Inception-ResNet-V2':
        base_model = applications.InceptionResNetV2(include_top=False,
                                                   weights='imagenet',
                                                   pooling='avg',
                                                   input_shape=(img_rows, img_cols, img_channel))

        lay_num_freeze = int(inceptionResNetV2_blocks[freeze_till_block,2])


    if tf_model == 'ResNet':
        base_model = applications.resnet.ResNet50(include_top=False,
                                                  weights='imagenet',
                                                  pooling='avg',
                                                  input_shape=(img_rows, img_cols, img_channel))

        lay_num_freeze = int(resnet_blocks[freeze_till_block,2])

    # Train base model
    if not full_retrain:
      base_model.trainable = full_retrain
    else:
      for layer in base_model.layers[:(lay_num_freeze)]:
        layer.trainable = False
      for layer in base_model.layers[lay_num_freeze:]:
        layer.trainable = True

    # Add top layer
    add_model = Sequential()
    add_model.add(Dense(1024, activation='relu',input_shape=base_model.output_shape[1:],
                        kernel_initializer = 'he_uniform',
                        bias_initializer = 'zeros'))
    add_model.add(Dropout(dr))
    add_model.add(Dense(1, activation='sigmoid'))

    # Create final model
    model = Model(inputs=base_model.input, outputs=add_model(base_model.output))

    # Compile model
    # https://www.pyimagesearch.com/2019/07/22/keras-learning-rate-schedules-and-decay/
    # https://machinelearningmastery.com/understand-the-dynamics-of-learning-rate-on-deep-learning-neural-networks/
    # https://stackoverflow.com/questions/60029027/decay-parameter-of-adam-optimizer-in-keras
    opt = optimizers.Adam(lr=lr, beta_1=0.9, beta_2=0.999, epsilon=1, decay=decay)

    metrics = [
      keras.metrics.TruePositives(name='tp'),
      keras.metrics.FalsePositives(name='fp'),
      keras.metrics.TrueNegatives(name='tn'),
      keras.metrics.FalseNegatives(name='fn'),
      keras.metrics.BinaryAccuracy(name='accuracy'),
      keras.metrics.Precision(name='precision'),
      keras.metrics.Recall(name='recall'),
      keras.metrics.AUC(name='auc'),
      ]

    # add regularization
    #add_regularization(model, regularizer=tf.keras.regularizers.l2(0.0001))

    model.compile(loss = loss_func, optimizer = opt, metrics=metrics)

    return model

def add_regularization(model, regularizer=tf.keras.regularizers.l2(0.0001)):

    if not isinstance(regularizer, tf.keras.regularizers.Regularizer):
      print("Regularizer must be a subclass of tf.keras.regularizers.Regularizer")
      return model

    for layer in model.layers:
      if layer.trainable:
        for attr in ['kernel_regularizer']:
            if hasattr(layer, attr):
              setattr(layer, attr, regularizer)

    # When we change the layers attributes, the change only happens in the model config file
    model_json = model.to_json()

    # Save the weights before reloading the model.
    tmp_weights_path = os.path.join(tempfile.gettempdir(), 'tmp_weights.h5')
    model.save_weights(tmp_weights_path)

    # load the model from the config
    model = tf.keras.models.model_from_json(model_json)

    # Reload the model weights
    model.load_weights(tmp_weights_path, by_name=True)

    return model

def fit_model(model, batch_size, epochs,
              # output_path,
              train_data, val_data):
    # Data augmentation
    # datagen = ImageDataGenerator(
    #         rotation_range = 180,
    #         width_shift_range = 0.2,
    #         height_shift_range = 0.2,
    #         zoom_range = [0.5,1.0],
    #         fill_mode = 'nearest')
    # datagen.fit(X_train)

    reduce_lr = ReduceLROnPlateau(monitor='val_loss',
                              patience=30,
                              verbose=1,
                              factor=0.5,
                              cooldown=0,
                              min_delta=0.0001,
                              min_lr=0.00001)

    # cp_weights_auc = ModelCheckpoint(output_path + "/weights.hdf5", monitor='val_auc', verbose=1,
    #                                 save_best_only=True, mode='max', period=1)
    # cp_weights_loss = ModelCheckpoint(output_path + "/weights_loss.hdf5", monitor='val_loss', verbose=1,
    #                                 save_best_only=True, mode='min', period=1)

    # filepath="weights-improvement-{epoch:02d}-{val_auc:.2f}.hdf5"
    # cp_weights_2 = ModelCheckpoint(output_path + '/' + filepath, monitor='val_auc', verbose=1, save_best_only=False, mode='max', period=50)

    # Fit model
    # history = model.fit(datagen.flow(X_train, y_train, batch_size=batch_size),
    #                 steps_per_epoch = len(X_train) / batch_size,
    #                 epochs = epochs,
    #                 verbose = 1,
    #                 validation_data=(X_val, y_val),
    #                 callbacks=[reduce_lr, cp_weights_auc, cp_weights_loss, cp_weights_2])

    history = model.fit(train_data,
                    steps_per_epoch = len(ind_train) / batch_size,
                    epochs = epochs,
                    verbose = 1)


    #pd.DataFrame(history.history).to_csv(output_path + "/history.csv")

    return model, history


# Calculate predictions, save plots etc
def summarize_model(model, history, file_add):

    # Get predictions
    preds_train = model.predict(X_train)
    preds_val = model.predict(X_val)
    preds_test = model.predict(X_test)

    # Calculate AUC on test set
    fpr_test, tpr_test, thresholds_keras = roc_curve(y_test, preds_test.ravel())
    auc_test = auc(fpr_test, tpr_test)

    # Get summary per TIFF
    labels_train = labels.iloc[ind_train,-1]
    labels_val = labels.iloc[ind_val,-1]
    labels_test = labels.iloc[ind_test,-1]

    df = pd.DataFrame()
    df['Tiff'] = np.concatenate((labels_train, labels_val, labels_test))
    df['set'] = np.concatenate((np.repeat('train', len(labels_train)), np.repeat('val', len(labels_val)), np.repeat('test', len(labels_test))))
    df['label'] = np.concatenate((y_train, y_val, y_test))
    df['pred'] = np.concatenate(((preds_train[:,0] >= 0.5).astype(int), (preds_val[:,0] >= 0.5).astype(int), (preds_test[:,0] >= 0.5).astype(int)))

    # Indicators for true / false positive / negative
    df['tn'] = ((df.label == 0) & (df.pred == 0)).astype(int)
    df['fn'] = ((df.label == 1) & (df.pred == 0)).astype(int)
    df['tp'] = ((df.label == 1) & (df.pred == 1)).astype(int)
    df['fp'] = ((df.label == 0) & (df.pred == 1)).astype(int)

    # Split into train and validation and test
    df_test_val = df[df['set'] != 'train']
    df_train = df[df['set'] == 'train']

    # Group by tiff to get total accuracy
    acc_test_val = df_test_val.groupby(['set','Tiff']).sum().reset_index()
    acc_test_val['perc_outside'] = acc_test_val.label / (acc_test_val.pred + acc_test_val.tn + acc_test_val.fn)
    acc_test_val['accuracy'] = (acc_test_val.tp + acc_test_val.tn) / (acc_test_val.pred + acc_test_val.tn + acc_test_val.fn)

    acc_train = df_train.groupby(['set','Tiff']).sum().reset_index()
    acc_train['perc_outside'] = acc_train.label / (acc_train.pred + acc_train.tn + acc_train.fn)
    acc_train['accuracy'] = (acc_train.tp + acc_train.tn) / (acc_train.pred + acc_train.tn + acc_train.fn)

    # Left join train acc per TIFF
    acc_per_tiff = pd.merge(acc_test_val, acc_train, how='left', on='Tiff')

    # Save as csv
    acc_per_tiff.to_csv(output_path + '/acc_per_tiff.csv')

    # Summarize history for AUC
    plt.figure()
    plt.plot(history.history['auc'])
    plt.plot(history.history['val_auc'])
    plt.title('model AUC')
    plt.ylabel('AUC')
    plt.xlabel('Epoch')
    plt.legend(['Train', 'Validation'], loc='upper left')
    plt.savefig(output_path + '/auc_dev.png')

    # Summarize history for AUC
    plt.figure()
    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title('model loss')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train', 'Validation'], loc='upper left')
    plt.savefig(output_path + '/loss_dev.png')

    # Plot confusion matrix - test set
    cm = confusion_matrix(y_test, (preds_test[:,0] >= 0.5).astype(int))
    disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                                  display_labels=['Inside','Outside'])
    disp = disp.plot(include_values=True, cmap=plt.cm.Blues,
                     ax=None, xticks_rotation='horizontal',values_format = '.5g')
    plt.savefig(output_path + '/confusion_test_' + file_add + '.png')

    return auc_test

# Layer start per tf_model - block
resnet_blocks = np.matrix([['ResNet', 0, 0],
           ['ResNet', 1, 7],
           ['ResNet', 2, 39],
           ['ResNet', 3, 81],
           ['ResNet', 4, 143]
           ])

inceptionV3_blocks = np.matrix([['Inception', 0, 42],
           ['Inception', 1, 65],
           ['Inception', 2, 88],
           ['Inception', 3, 102],
           ['Inception', 4, 134],
           ['Inception', 5, 166],
           ['Inception', 6, 198],
           ['Inception', 7, 230],
           ['Inception', 8, 250],
           ])

inceptionResNetV2_blocks = np.matrix([['Inception', 0, 1],
           ['Inception', 1, 60], # Inception-ResNet-A block
           ['Inception', 2, 288], # Inception-ResNet-B block
           ['Inception', 3, 595],
           ['Inception', 4, 631], # Inception-ResNet-C block
           ['Inception', 5, 777]
           ])

from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

# Clear any logs from previous runs
!rm -rf ./logs/

list_main_path = ['/content/drive/My Drive/Esmee/Data/Patches_clean_small_2/']  # Path where data is in (per class one folder)
size = [224,224]                                                                # input size of model (for Inception and ResNet: 224 x 224)

list_class_imbs = ['Oversample']
list_class_imbs_type = ['tiff']
list_independent = [False]                          # boolean to select independent test set or randomly shuffle train and test
list_tf_model = ['ResNet']                          # transfer learning model used (Inception or Resnet)
#list_full_retrain = [False]                        # boolean to also retrain base (true) or only top layer (false)
list_loss_func = ['binary_crossentropy']            # loss function to optimize
list_lr = [0.001]                                   # learning rate used in Adam optimizer
list_decay = [0]                                    # decay parameter used in Adam optimizer # after each epoch: https://stackoverflow.com/questions/60029027/decay-parameter-of-adam-optimizer-in-keras
list_dr = [0.4]                                     # dropout rate used
batch_size = 4 * tpu_strategy.num_replicas_in_sync # batch size used for training
epochs = 150                                        # number of epochs to train model

hyperparams_grid_1 = itertools.product(list_main_path, list_class_imbs, list_independent, list_tf_model, [False], [0], list_loss_func, list_lr, list_decay, list_dr)
hyperparams_grid_2 = itertools.product(list_main_path, list_class_imbs, list_independent, ['Inception-ResNet-V2'], [True], [2], list_loss_func, list_lr, list_decay, list_dr)
#hyperparams_grid_3 = itertools.product(list_main_path, list_class_imbs, list_independent, ['InceptionV3'], [True], list(range(7,9)), list_loss_func, list_lr, list_decay, list_dr)
hyperparams_grid_full = list(itertools.chain(hyperparams_grid_1)) #list(itertools.chain(hyperparams_grid_1, hyperparams_grid_2, hyperparams_grid_3))

count = 0
for params in hyperparams_grid_full:
    main_path = params[0]
    class_imb = params[1]
    class_imb_type = 'class' #'tiff'
    independent = params[2]
    tf_model = params[3]
    full_retrain = params[4]
    freeze_till_block = params[5]
    loss_func = params[6]
    lr = params[7]
    decay = params[8]
    dr = params[9]

    folder_name = tf_model + '_' + class_imb + '_type=' + class_imb_type + '_iid=' + str(independent) + '_' + 'retrain=' + str(full_retrain) + '_' + str(freeze_till_block) + '_'+ loss_func + '_'+ str(lr) + '_'+ str(decay) + '_' + str(dr) + '_' + str(epochs)
    output_path = '/content/drive/My Drive/Esmee/Results/' + folder_name
    try:
        os.makedirs(output_path)
    except:
        pass

    print('Reading data')
    data, labels, enc_labels = read_data(list_main_path[0], size)

    print('Splitting data into train, validation and test')
    ind_train, ind_test, ind_val = split_data(data, enc_labels, labels, independent)

    if class_imb != 'No':
      ind_train = balance_dataset(enc_labels, ind_train, class_imb, class_imb_type)

    print('Getting datasets')
    X_train, y_train, X_val, y_val, X_test, y_test = get_data_sets(data, enc_labels, ind_train, ind_val, ind_test)

    del data, enc_labels
    K.clear_session()
    gc.collect()
    time.sleep(120)

    # Creating the model in the TPUStrategy scope means we will train the model on the TPU
    print('Building model ' + tf_model
          + ' model with parameters: train base = ' + str(full_retrain)
          + ', freeze till block = ' + str(freeze_till_block)
          + ', learning rate = ' + str(lr)
          + ', decay rate = ' + str(decay)
          + ', dropout rate = ' + str(dr))

    # with tpu_strategy.scope():
    #   model = build_model(tf_model, full_retrain, freeze_till_block, loss_func, lr, decay, dr)

    # print('Converting to data arrays to TF prefetch datasets (iteratable datasets)')
    # train_data = convert_to_tf_prefetchdataset(X_train, y_train, batch_size)  # multiple batches for train data
    # val_data = convert_to_tf_prefetchdataset(X_val, y_val, len(y_val))        # validation data all in one batch

    # print('Fitting model')
    # model, history = fit_model(model, batch_size, epochs, output_path, train_data, val_data)

    # # best model:
    # auc_test_org = summarize_model(model, history, 'org')
    # # best model in terms of AUC:
    # model = load_model(output_path + '/weights.hdf5')
    # auc_test_AUC = summarize_model(model, history, 'AUC')
    # # best model in terms of loss:
    # model = load_model(output_path + '/weights_loss.hdf5')
    # auc_test_loss = summarize_model(model, history, 'LOSS')

    # print(auc_test_org)
    # print(auc_test_AUC)
    # print(auc_test_loss)

    # print('Clearing RAM')
    # del X_train, X_val, X_test, y_train, y_val, y_test
    # del model, history
    # K.clear_session()
    # gc.collect()

with tpu_strategy.scope():
  base_model = applications.InceptionResNetV2(include_top=False,
                                                    weights='imagenet',
                                                    pooling='avg',
                                                    input_shape=(224, 224, 3))

  lay_num_freeze = int(inceptionResNetV2_blocks[freeze_till_block,2])

  # Train base model
  if not full_retrain:
    base_model.trainable = full_retrain
  else:
    for layer in base_model.layers[:(lay_num_freeze)]:
      layer.trainable = False
    for layer in base_model.layers[lay_num_freeze:]:
      layer.trainable = True

  # Add top layer
  add_model = Sequential()
  add_model.add(Dense(1024, activation='relu',input_shape=base_model.output_shape[1:],
                      kernel_initializer = 'he_uniform',
                      bias_initializer = 'zeros'))
  add_model.add(Dropout(dr))
  add_model.add(Dense(1, activation='sigmoid'))

  # Create final model
  model = Model(inputs=base_model.input, outputs=add_model(base_model.output))

  # Compile model
  # https://www.pyimagesearch.com/2019/07/22/keras-learning-rate-schedules-and-decay/
  # https://machinelearningmastery.com/understand-the-dynamics-of-learning-rate-on-deep-learning-neural-networks/
  # https://stackoverflow.com/questions/60029027/decay-parameter-of-adam-optimizer-in-keras
  opt = tf.keras.optimizers.Adam(lr=lr, beta_1=0.9, beta_2=0.999, epsilon=1, decay=decay)

  metrics = [
    keras.metrics.TruePositives(name='tp'),
    keras.metrics.FalsePositives(name='fp'),
    keras.metrics.TrueNegatives(name='tn'),
    keras.metrics.FalseNegatives(name='fn'),
    keras.metrics.BinaryAccuracy(name='accuracy'),
    keras.metrics.Precision(name='precision'),
    keras.metrics.Recall(name='recall'),
    keras.metrics.AUC(name='auc'),
    ]

  #   # add regularization
  #   #add_regularization(model, regularizer=tf.keras.regularizers.l2(0.0001))

  model.compile(loss = loss_func, optimizer = opt, metrics=metrics)

print('Converting to data arrays to TF prefetch datasets (iteratable datasets)')
train_data = convert_to_tf_prefetchdataset(X_train, y_train, batch_size)

for i in ind_test:
      img_name = labels.Image[i]
      img_cat = labels.Label[i]
      if img_cat == 'Outside':
        img = cv2.imread(main_path + '/Outside/' + img_name)
      else:
        img = cv2.imread(main_path + '/Inside/' + img_name)

      try:
        os.makedirs(output_path + '/test_set/' + img_cat + '/')
      except:
        pass
      cv2.imwrite(output_path + '/test_set/' + img_cat + '/' + img_name, img)