# -*- coding: utf-8 -*-
"""Split_random_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nA0pw16Ybras_Y_IBa1aQhF4XhA-HMS0
"""

from google.colab import drive
drive.mount('/content/drive', force_remount = True)

# Import packages
import cv2
import os, gc, sys, glob
import shutil
import pandas as pd
import numpy as np
from tqdm import tqdm
from pathlib import Path
import matplotlib.pyplot as plt
import itertools
import random
import datetime
import time

import imblearn
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler

from sklearn import model_selection
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, GroupShuffleSplit, StratifiedKFold
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.utils import shuffle
from skimage.transform import rotate
import scipy.ndimage as ndi

from subprocess import check_output

import tensorflow as tf

#from tensorflow.python.framework.ops import disable_eager_execution

import tensorflow.keras
from tensorflow.keras import optimizers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.models import Model, load_model
from tensorflow.keras import applications
from tensorflow.keras.callbacks import ReduceLROnPlateau, TensorBoard
from tensorflow.keras.optimizers import Adam

from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.metrics import categorical_accuracy
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ModelCheckpoint, CSVLogger
import tensorflow.keras.backend as K

print(tf.__version__)

# Read single image
def read_img(img_path, size):
    img = cv2.imread(str(img_path))
    img = cv2.resize(img, (size[0], size[1]))
    return img

# Loading data and labels
def list_images(main_path, size):
    folders = [a for a in os.listdir(main_path) if os.path.isdir(os.path.join(main_path, a)) and 'dir' not in a]
    dirs = [main_path + '/' + f for f in folders]

    images = []

    for i in range(len(dirs)):
      count=1
      for img_path in Path(dirs[i]).glob('**/*.png'):
          images.append([img_path, os.path.basename(img_path), folders[i].split('_')[0]])
          if count%1000==0:
            print('Loading data from dir ' + folders[i] + ': ' + str(count))
          count +=1

    images = pd.DataFrame(images, columns = ['Full_path', 'Image','Label'])
    images['tiff'] = [name[:name.find('_')] for name in images['Image']]

    # join subject info
    mapping = pd.read_csv(main_path + '/mapping.csv', sep=';')
    images =  images.merge(mapping, on='tiff', how='left')

    return images

# Split train, validation and test set
# param independent determines if test data is independent or not
# (random or specific WSIs excluded from training)
def split_data(images, independent):

    indices_org = [i for i, x in enumerate(images.Image) if '_rot.png' not in x]
    images_org = images.iloc[indices_org, :]

    if not independent:
      # Split train - test
      ind_train, ind_test = train_test_split(indices_org,
                                              test_size=0.10,
                                              random_state=42,
                                              stratify=images_org.Label,
                                              shuffle=True)
      # Split train - validation
      ind_train, ind_val = train_test_split(ind_train,
                                              test_size=0.2/0.9,
                                              random_state=42,
                                              stratify=[images.Label[i] for i in ind_train],
                                              shuffle=True)

    elif independent:
      # First split train and test set
      unique_patients = images_org.patient.unique()
      train_target_n = int(.9 * images_org.shape[0])
      shuffled_patients = np.random.permutation(unique_patients)

      p_count = images_org.patient.value_counts()

      mapping = p_count.reindex(shuffled_patients).cumsum() <= train_target_n
      mask = images_org.patient.map(mapping)

      ind_train_temp = [indices_org[i] for i in range(len(indices_org)) if list(mask)[i]]
      ind_test = [indices_org[i] for i in range(len(indices_org)) if indices_org[i] not in ind_train_temp]

      # Now split train set into train and validation set
      unique_patients = images_org.patient[ind_train_temp].unique()
      train_target_n = int(.7/.9 * images_org.iloc[ind_train_temp,:].shape[0])
      shuffled_patients = np.random.permutation(unique_patients)

      p_count = images_org.patient[ind_train_temp].value_counts()

      mapping = p_count.reindex(shuffled_patients).cumsum() <= train_target_n
      mask = images_org.patient[ind_train_temp].map(mapping)

      ind_train =  [ind_train_temp[i] for i in range(len(ind_train_temp)) if list(mask)[i]]
      ind_val = [ind_train_temp[i] for i in range(len(ind_train_temp)) if ind_train_temp[i] not in ind_train]

    return ind_train, ind_val, ind_test

# Tackle class imbalanceness: Choose under- or oversampling
def balance_dataset(images, ind_train, train_strategy):
      # Define strategy
      if train_strategy == 'None':
        fn_train = [images.Image[i] for i in ind_train]
      elif train_strategy == 'Ext_oversample': # oversampling done externally in Python by rotating all images
        rot180_train_imgs = [images.Image[i].replace('.png','_rot.png') for i in ind_train if images.Label[i] == 'Inside']
        fn_train = [images.Image[i] for i in ind_train] + rot180_train_imgs
      else:
        if train_strategy == 'Oversample':
          sample_strat = RandomOverSampler(sampling_strategy='minority')
        if train_strategy == 'Undersample':
          sample_strat = RandomUnderSampler(sampling_strategy='majority')

        # Fit and apply the transform
        images_train = images[ind_train]
        ind_new, images_balanced = sample_strat.fit_resample(np.arange(len(images)).reshape(-1, 1), images)
        ind_new = ind_train[ind_new].squeeze()
        fn_train = [file_names[i] for i in ind_new]

      ind_train_new = [list(images.Image).index(fn) for fn in fn_train]


      return ind_train_new

# Loading data and labels
def resize_data(main_path, size):
    folders = [a for a in os.listdir(main_path) if os.path.isdir(os.path.join(main_path, a))]
    dirs = [main_path + '/' + f for f in folders]

    images = []

    for i in range(len(dirs)):
      count=1
      for img_path in Path(dirs[i]).glob('**/*.png'):
          img = read_img(img_path, size)
          cv2.imwrite(str(img_path), img)
          if count%1000==0:
            print('Loading data from dir ' + folders[i] + ': ' + str(count))
          count +=1

threshold = 0.2
data_path = '/content/drive/My Drive/Esmee/Data_random/Patches_cutoff_clean_' + str(threshold) + '/' # Path where data is in (per class one folder)
size = [224,224]      # input size of model (for Inception and ResNet: 224 x 224)

independent_sets = False
class_imb = 'Ext_oversample'

# Make train, val and test folders
train_dir = os.path.join(data_path, 'train_dir')
val_dir = os.path.join(data_path, 'val_dir')
test_dir = os.path.join(data_path, 'test_dir')
try:
  os.mkdir(train_dir)
  os.mkdir(val_dir)
  os.mkdir(test_dir)
except:
  pass

# Make class folders
outside_train_dir = os.path.join(train_dir, 'Outside')
inside_train_dir = os.path.join(train_dir, 'Inside')
outside_val_dir = os.path.join(val_dir, 'Outside')
inside_val_dir = os.path.join(val_dir, 'Inside')
outside_test_dir = os.path.join(test_dir, 'Outside')
inside_test_dir = os.path.join(test_dir, 'Inside')
try:
  os.mkdir(outside_train_dir)
  os.mkdir(inside_train_dir)
  os.mkdir(outside_val_dir)
  os.mkdir(inside_val_dir)
  os.mkdir(outside_test_dir)
  os.mkdir(inside_test_dir)
except:
  pass

outside_train_dir_black = outside_train_dir.replace('random','black').replace('_clean','')
inside_train_dir_black = inside_train_dir.replace('random','black').replace('_clean','')
outside_val_dir_black = outside_val_dir.replace('random','black').replace('_clean','')
inside_val_dir_black = inside_val_dir.replace('random','black').replace('_clean','')
outside_test_dir_black = outside_test_dir.replace('random','black').replace('_clean','')
inside_test_dir_black = inside_test_dir.replace('random','black').replace('_clean','')

# Save all images in corresponding directory (train, validation, test)
# To overcome RAM issues later on
print('Saving train images in corresponding directory')
count=1
for img_path in Path(outside_train_dir_black).glob('**/*.png'):
  img_name = os.path.basename(img_path)

  if '(1)' not in img_name:
    random_path = data_path + '/Outside/' + img_name
    target_path = os.path.join(outside_train_dir, img_name)

    # Copy file
    shutil.copyfile(random_path, target_path)

    count+=1
    if count%1000 == 0:
      print('Saving train images: ' + str(count))

count=1
for img_path in Path(inside_train_dir_black).glob('**/*.png'):
  img_name = os.path.basename(img_path)
  if '(1)' not in img_name:
    if '_rot' in img_name:
      random_path = data_path + '/Inside_oversample/' + img_name
    else:
      random_path = data_path + '/Inside/' + img_name
    target_path = os.path.join(inside_train_dir, img_name)

    # Copy file
    try:
      shutil.copyfile(random_path, target_path)
    except:
      pass

    count+=1
    if count%1000 == 0:
      print('Saving train images: ' + str(count))


print('Saving validation images in corresponding directory')
count=1
for img_path in Path(outside_val_dir_black).glob('**/*.png'):
  img_name = os.path.basename(img_path)
  random_path = data_path + '/Outside/' + img_name
  target_path = os.path.join(outside_val_dir, img_name)

  # Copy file
  try:
    shutil.copyfile(random_path, target_path)
  except:
    pass

  count+=1
  if count%1000 == 0:
    print('Saving validation images: ' + str(count))

count=1
for img_path in Path(inside_val_dir_black).glob('**/*.png'):
  img_name = os.path.basename(img_path)
  random_path = data_path + '/Inside/' + img_name
  target_path = os.path.join(inside_val_dir, img_name)

  # Copy file
  try:
    shutil.copyfile(random_path, target_path)
  except:
    pass

  count+=1
  if count%1000 == 0:
    print('Saving validation images: ' + str(count))

print('Saving test images in corresponding directory')
count=1
for img_path in Path(outside_test_dir_black).glob('**/*.png'):
  img_name = os.path.basename(img_path)
  random_path = data_path + '/Outside/' + img_name
  target_path = os.path.join(outside_test_dir, img_name)

  # Copy file
  try:
    shutil.copyfile(random_path, target_path)
  except:
    pass

  count+=1
  if count%1000 == 0:
    print('Saving test images: ' + str(count))

count=1
for img_path in Path(inside_test_dir_black).glob('**/*.png'):
  img_name = os.path.basename(img_path)
  random_path = data_path + '/Inside/' + img_name
  target_path = os.path.join(inside_test_dir, img_name)

  # Copy file
  try:
    shutil.copyfile(random_path, target_path)
  except:
    pass

  count+=1
  if count%1000 == 0:
    print('Saving test images: ' + str(count))

# Resize images to 224 x 224 for all sets (train, validation, test)
dataset_dirs = [train_dir, val_dir, test_dir]
for d in dataset_dirs:
  resize_data(d, size)